# Generated by Django 6.0.7 on 2026-08-25 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Internal id (e.g. 'compound-wall-cleaning'). Don't change after creation.", unique=True)),
                ('label', models.CharField(help_text="Shown to the customer, e.g. 'Compound Wall Construction'.", max_length=150)),
                ('description', models.CharField(blank=True, default='', help_text="Short helper text shown under the option, e.g. 'Boundary wall build or repair'.", max_length=255)),
                ('pricing_mode', models.CharField(choices=[('flat', 'Flat Price'), ('per_sqft', 'Price per sq.ft')], default='per_sqft', max_length=10)),
                ('flat_price', models.PositiveIntegerField(blank=True, help_text="₹ fixed amount. Used only when pricing mode is 'Flat Price'.", null=True)),
                ('price_per_sqft', models.PositiveIntegerField(blank=True, help_text="₹ per sq.ft, multiplied by the area the customer enters. Used only when pricing mode is 'Price per sq.ft'.", null=True)),
                ('icon', models.CharField(choices=[('wall', 'Compound Wall'), ('home', 'Home'), ('building', 'Building'), ('wrench', 'Repair / Wrench'), ('paintbrush', 'Paint'), ('sparkles', 'Remodel / Sparkles')], default='wall', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this service from the request form without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(help_text='Typed address / plot details.', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sqft', models.PositiveIntegerField(blank=True, help_text='Only needed when the selected service type prices per sq.ft.', null=True)),
                ('requirement_text', models.TextField(help_text='What the customer typed describing what they need done.')),
                ('estimated_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.servicetype')),
            ],
            options={
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
