# Generated by Django 6.0.7 on 2026-08-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ServiceTypeCityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text="Stored lowercase/trimmed automatically. Match the city as it appears from the map (e.g. 'Hyderabad').", max_length=100)),
                ('flat_price', models.PositiveIntegerField(blank=True, help_text='Overrides the flat price for this city. Leave blank to fall back to the default.', null=True)),
                ('price_per_sqft', models.PositiveIntegerField(blank=True, help_text='Overrides the ₹/sq.ft rate for this city. Leave blank to fall back to the default.', null=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_prices', to='service_requests.servicetype')),
            ],
            options={
                'verbose_name': 'Service City Price',
                'verbose_name_plural': 'Service City Prices',
                'ordering': ['city_name'],
                'unique_together': {('service_type', 'city_name')},
            },
        ),
    ]
