# Generated by Django 6.0.7 on 2026-07-16 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('new_construction', 'New Construction'), ('renovation', 'Renovation'), ('commercial', 'Commercial'), ('interior', 'Interior Design'), ('other', 'Other')], default='new_construction', max_length=30)),
                ('plot_size', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('called', 'Called'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
