# Generated by Django 6.0.7 on 2026-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
