# Generated by Django 6.0.7 on 2026-08-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField(blank=True, help_text="Flat cost in ₹, regardless of plot size. Leave blank if using 'cost per sq.ft' instead.", null=True)),
                ('cost_per_sqft', models.PositiveIntegerField(blank=True, help_text="₹ per sq.ft of plot size — scales with the project. Leave blank if using 'flat cost' instead.", null=True)),
                ('icon', models.CharField(choices=[('wrench', 'Wrench'), ('sparkles', 'Sparkles')], default='sparkles', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': 'Add-ons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate_per_sqft', models.PositiveIntegerField(help_text='Base construction rate in ₹ per sq.ft for this city.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this city from the estimator without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'City Rate',
                'verbose_name_plural': 'City Rates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Internal id, don't change after creation.", unique=True)),
                ('label', models.CharField(max_length=100)),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = no change, 1.15 = 15% more expensive than a standard residential build.', max_digits=4)),
                ('icon', models.CharField(choices=[('home', 'Home'), ('building', 'Building'), ('layers', 'Layers')], default='building', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Construction Type',
                'verbose_name_plural': 'Construction Types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorQualityTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Internal id (e.g. 'basic'). Don't change this after creation — the frontend won't recognise a changed key.", unique=True)),
                ('label', models.CharField(help_text="Shown to the customer, e.g. 'Premium'.", max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text="Applied on top of the city's base rate. 1.00 = same as base rate, 1.70 = 70% more expensive.", max_digits=4)),
                ('description', models.CharField(help_text="What this tier contains, e.g. 'Designer finish, modular interiors'.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first, top to bottom.')),
            ],
            options={
                'verbose_name': 'Quality Tier',
                'verbose_name_plural': 'Quality Tiers',
                'ordering': ['order'],
            },
        ),
    ]
