# Generated by Django 6.0.7 on 2026-08-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorBreakdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=3, help_text='Share of base cost, e.g. 0.380 = 38%.', max_digits=4)),
                ('color_hex', models.CharField(default='#c9a84c', help_text='Bar color, e.g. #c9a84c', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Breakdown Item',
                'verbose_name_plural': 'Breakdown Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorSpecCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Spec Category',
                'verbose_name_plural': 'Spec Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorTimelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_months', models.PositiveIntegerField(default=6)),
                ('per_floor_months', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('sqft_divisor', models.PositiveIntegerField(default=900, help_text='Plot size is divided by this number and added as months. Lower = longer timelines for big plots.')),
            ],
            options={
                'verbose_name': 'Timeline Formula',
                'verbose_name_plural': 'Timeline Formula',
            },
        ),
        migrations.CreateModel(
            name='EstimatorTierSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_label', models.CharField(help_text="Shown to the customer, e.g. 'Premium Vitrified / Marble'.", max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.estimatorspeccategory')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='estimator.estimatorqualitytier')),
            ],
            options={
                'verbose_name': 'Tier Spec Item',
                'verbose_name_plural': 'Tier Spec Items',
                'ordering': ['category__order'],
                'unique_together': {('tier', 'category')},
            },
        ),
    ]
