# Generated by Django 6.0.7 on 2026-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_estimatorbreakdownitem_estimatorspeccategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorFloorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Ground', 'G+1', 'G+2'", max_length=50)),
                ('floor_count', models.PositiveIntegerField(help_text='Numeric floor count used in the formula, e.g. 1, 2, 3')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Cost multiplier for this many floors relative to single floor.', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
