# Generated by Django 6.0.7 on 2026-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_estimatorflooroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatorqualitytier',
            name='description',
            field=models.CharField(blank=True, default='', help_text="What this tier contains, e.g. 'Designer finish, modular interiors'.", max_length=255),
        ),
    ]
