# Generated by Django 6.0.7 on 2026-08-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='ReliaState', max_length=255)),
                ('contact_email', models.EmailField(default='hello@iconbuilderindia.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=20)),
                ('domain', models.CharField(default='iconbuilderindia.com', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
