# Generated by Django 6.0.7 on 2026-08-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstore',
            name='otp',
            field=models.CharField(max_length=30),
        ),
    ]
