# Generated by Django 6.0.7 on 2026-07-31 10:58

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], max_length=20)),
                ('location', models.CharField(default='Bangalore', max_length=100)),
                ('beds', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planning', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.portfolioproject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
