# Generated by Django 6.0.7 on 2026-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Row House', 'Row House'), ('Plot', 'Plot'), ('Commercial', 'Commercial')], max_length=20),
        ),
    ]
