# Generated by Django 6.0.7 on 2026-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioproject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Row House', 'Row House'), ('Plot', 'Plot'), ('Commercial', 'Commercial'), ('Real Images', 'Real Images')], max_length=20),
        ),
    ]
